@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Container(loadBalancer, "Load Balancer", "Nginx", "Uses round-robin")
Container(apiGateway, "API Gateway", "Istio")
Container(relationSystem, "Relation System", "Software system", "Stores relations (friends, subscribers, etc.) between users")

System_Boundary(profileSystem, "Profile System") {
    Container(profileService, "Profile Service", "Go", "Handles user profiles")
    ContainerDb(profileDatabase, "Profile database", "PostgreSQL", "Stores user profiles")
}

Rel(user, loadBalancer, "Views user's profile", "REST")
Rel(loadBalancer, apiGateway, "Views user's profile", "REST")
Rel(apiGateway, profileService, "Views user's profile", "GRPC")
Rel(profileService, relationSystem, "Gets relations for profile", "GRPC")
Rel(profileService, profileDatabase, "CRUD profiles")
@enduml